### ISSUE TITLE
Invalid Trajectories Created

### ISSUE THREAD

**Issue by danem** [ros-planning/moveit_task_constructor#233]
Using MTC f99d03386ad8751fb0ade71c09a9810019a950ad.

I am successfully planning a pick using MTC. MTC reports that the solution has been successfully found and the plan is correctly visualized in Rviz. However, when trying to execute this solution using the Execute capability, the [generated trajectory ](https://github.com/ros-planning/moveit/blob/master/moveit_ros/planning/plan_execution/src/plan_execution.cpp#L371 ) contains bad data which is rejected by my trajectory controller with the error "Trajectory message contains waypoints that are not strictly increasing in time.". 

What could be causing the discrepancy between the visualized trajectory and the one being sent to the trajectory controller?

An example of what is sent to the `follow_trajectory` endpoint:

```
 points: 
      - 
        positions: [0.7397, -0.0030679615234375, -0.020325245092773437, 2.0635876197021483, -3.1392916288574217, 0.16873788378906251, 3.1396751240478515]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        effort: []
        time_from_start: 
          secs: 0
          nsecs:         0
      - 
        positions: [0.7397001240013277, -0.03246895310226966, -0.02441177174213565, 2.07099413161763, -3.102367452038901, 0.2030662516651845, 3.1193793785168675]
        velocities: [8.835592602350391e-07, -0.20949387274113646, -0.029118143568025733, 0.052774371929507624, 0.2630995889628328, 0.2446034077445519, -0.14461533788934003]
        accelerations: [3.3711408699462948e-06, -0.7993050236676782, -0.11109765707829938, 0.20135586808443628, 1.0038328111044719, 0.9332622957333059, -0.5517668109423922]
        effort: []
        time_from_start: 
          secs: 0
          nsecs: 198462088 points: 

/ ...
// Bad data starts
///
---
header: 
  seq: 23
  stamp: 
    secs: 1613168986
    nsecs: 518691260
  frame_id: ''
goal_id: 
  stamp: 
    secs: 1613168986
    nsecs: 518692193
  id: "/move_group-38-1613168986.518692193"
goal: 
  trajectory: 
    header: 
      seq: 0
      stamp: 
        secs: 0
        nsecs:         0
      frame_id: "world"
    joint_names: [Joint_1, Joint_2, Joint_3, Joint_4, Joint_5, Joint_6]
    points: 
      - 
        positions: [-1.7745037288831231, -0.21050136321802213, 2.405817313134492, -1.6909986578677245, 1.405934550892721, 2.2052587505959518]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        effort: []
        time_from_start: 
          secs: 0
          nsecs:         0
      - 
        positions: [-1.7745037288831231, -0.21050136321802213, 2.405817313134492, -1.6909986578677245, 1.405934550892721, 2.2052587505959518]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        effort: []
        time_from_start: 
          secs: 0
          nsecs:         0
      - 
        positions: [-1.7745037288831231, -0.21050136321802213, 2.405817313134492, -1.6909986578677245, 1.405934550892721, 2.2052587505959518]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        effort: []
        time_from_start: 
          secs: 0
          nsecs:         0
```

[Here](https://giant.gfycat.com/MarvelousFamousCod.webm) is a video of the described behavior.

And [here](https://gist.github.com/danem/515d1d9ae7c116eadd9e04b6cf7000dc) is the code I use to plan and execute my task.

Edit:

[Here](https://github.com/ros-planning/moveit_task_constructor/files/5993198/mtc_solution.txt) is the `ExecuteTaskSolutionActionGoal` that generates the faulty trajectory. 

[Here](https://github.com/ros-planning/moveit_task_constructor/files/5993203/trajectory.txt) is the resultant trajectory that gets sent to the position controller. Notice that the last trajectory seems to be the problem.
