### ISSUE TITLE
MoveRelative does not respect cartesian lift up

### ISSUE THREAD

**Issue by captain-yoshi** [ros-planning/moveit_task_constructor#399]
Stumbled upon a weird behavior where the cartesian solver with the `MoveRelative` stage seems to use a sampling based planner in one of the solutions (similar to the lift_object in the demo). Hard to replicate and may be due to my configuration of the task. 

```yaml
# solver parameters
type: cartesian
step_size: 0.01                    # step size between consecutive waypoints
jump_threshold: 1.5                # acceptable fraction of mean joint motion per step
min_fraction: 1.0                  # fraction of motion required for success
max_velocity_scaling_factor: 0.1
max_acceleration_scaling_factor: 0.1
```

https://user-images.githubusercontent.com/32679594/204626313-72ce6d74-2e10-4cb5-b5af-2bca8c43b15e.mp4
